export const quotationSchema = {
    $schema: 'http://json-schema.org/draft-07/schema#',
    $id: 'http://example.com/quotation.schema.json',
    title: 'Quotation',
    description: 'Quotation',
    type: 'object',
    properties: {
        quote_date: {
            type: 'string',
            // format: 'date',
            title: 'Quotation date',
            description: 'Quotation Date',
            required: true,
        },
        rep: {
            type: 'integer',
            // exclusiveMinimum: 0,
            title: 'Rep',
            description: 'ID of sales staff (auth_user)',
            required: true,
        },
        cusID: {
            type: 'integer',
            // exclusiveMinimum: 0,
            title: 'Customer ID',
            description: 'ID of customer (Partymaster)',
            required: true,
        },
        billing_address: {
            type: 'integer',
            // exclusiveMinimum: 0,
            title: 'Billing address',
            description: 'ID of billing address (Contact)',
            required: true,
        },
        shipping_address: {
            type: 'integer',
            // exclusiveMinimum: 0,
            title: 'Shipping address',
            description: 'ID of shipping address (Contact)',
            required: true,
        },
        total_amt: {
            type: 'number',
            multipleOf: 0.01,
            title: 'Total amount',
            description: 'Total amount of Quotation',
            required: true,
        },
        int_Remark: {
            type: 'string',
            title: 'Internal remark',
            description: 'Internal Remarks',
        },
        ext_Remark: {
            type: 'string',
            title: 'External remark',
            description: 'External Remarks',
        },
        status: {
            type: 'integer',
            enum: [1, 2],
            // enum_titles: ["New", "Pending"],
            // exclusiveMinimum: 0,
            title: 'Status',
            description: 'ID of status',
            required: true,
        },
        created_by: {
            type: 'integer',
            exclusiveMinimum: 0,
            description: 'ID of user',
        },
        modified_by: {
            type: 'integer',
            exclusiveMinimum: 0,
            private: true,
            description: 'ID of user',
        },
    },
    required: [
        'quote_date',
        'rep',
        'cusID',
        'billing_address',
        'shipping_address',
        'total_amt',
        'status',
    ],
}
